import type { Product, Category } from './types';
import { HeadIcon, EyeIcon, EarIcon, MouthIcon, ArmIcon, BodyIcon, LegIcon, BrainIcon } from './components/Icons';

export const categories: Category[] = [
    { id: 'head-neck', name: 'Head & Neck', icon: HeadIcon },
    { id: 'vision', name: 'Eyes & Vision', icon: EyeIcon },
    { id: 'hearing', name: 'Ears & Hearing', icon: EarIcon },
    { id: 'speech', name: 'Mouth & Speech', icon: MouthIcon },
    { id: 'mobility', name: 'Legs & Feet', icon: LegIcon },
    { id: 'daily-living', name: 'Hands & Arms', icon: ArmIcon },
    { id: 'support', name: 'Torso & Body', icon: BodyIcon },
    { id: 'mental-health', name: 'Mental Wellness', icon: BrainIcon },
]

export const products: Product[] = [
  {
    id: 1,
    name: 'Advanced Head Support System',
    description: 'A padded collar and mounting system for wheelchairs, providing exceptional stability and comfort for users with limited head or neck control.',
    price: 56.35,
    category: 'head-neck',
    imageUrl: 'https://th.bing.com/th/id/R.b55b4bf6cbbbd7abc86db61083afb962?rik=iMgOV5HbB1cozQ&pid=ImgRaw&r=0',
  },
  {
    id: 2,
    name: 'Joystick Control',
    description: 'Control computers, wheelchairs, and other devices with slight head movements. Highly sensitive and customizable for user needs.',
    price: 123.98,
    category: 'head-neck',
    imageUrl: 'https://www.gilaniengineering.com.au/wp-content/uploads/2022/11/How-Does-a-Wheelchair-Joystick-Work-800x533.webp',
  },
  
  
  {
    id: 3,
    name: 'Refreshable Braille Display',
    description: 'An electronic device that translates screen text into a refreshable Braille format, providing tactile access to digital information.',
    price: 84.53,
    category: 'vision',
    imageUrl: 'https://tse4.mm.bing.net/th/id/OIP.EU7wd2Ievtpn43tXS4gKAgHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 4,
    name: 'Digital Handheld Magnifier',
    description: 'A portable device that enlarges text and images, featuring multiple color modes and brightness settings for optimal viewing.',
    price: 169.06,
    category: 'vision',
    imageUrl: 'https://visionaid.org/wp-content/uploads/2023/07/Digital-Magnifier-4-scaled.jpg',
  },
  {
    id: 5,
    name: 'Clarity Hearing Aids (Pair)',
    description: 'Small, discreet electronic devices that fit behind the ear to amplify sound, featuring noise cancellation and Bluetooth connectivity.',
    price: 56.35,
    category: 'hearing',
    imageUrl: 'https://tse2.mm.bing.net/th/id/OIP.AdZ3KqwhFqZGiG-RcErEcQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 6,
    name: 'Cochlear Implant Processor',
    description: 'An advanced sound processor for surgically implanted devices, providing a rich sense of sound to individuals who are profoundly deaf.',
    price: 1127.09,
    category: 'hearing',
    imageUrl: 'https://th.bing.com/th/id/OIP.9Y61Ei8q4iJ_OTToJgQIAAHaDf?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 7,
    name: 'Orator AAC Communication Tablet',
    description: 'A dedicated tablet with symbol-based communication apps. Users can select symbols or type, and the device speaks the message aloud.',
    price: 699,
    category: 'speech',
    imageUrl: 'https://th.bing.com/th/id/R.850c953a30ae86cf690689ca94e359fc?rik=e4IrQGAo0I5Y2g&riu=http%3a%2f%2fwww.speechbuddy.com%2fblog%2fwp-content%2fuploads%2f2012%2f03%2fspeech4.png&ehk=DOqSkTMG07f5OJjzPAU6IhD%2bpC4cF7mNTksPpULsCzw%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    id: 8,
    name: 'MyoProsthetic Limb (Arm)',
    description: 'A highly functional artificial arm controlled by the user\'s own muscle movements, offering intuitive control and dexterity.',
    price: 732.61,
    category: 'daily-living',
    imageUrl: 'https://th.bing.com/th/id/OIP.IqArqT7KziRX1-erqS2rBQHaEK?w=285&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
  },
  {
    id: 9,
    name: 'SteadyGrip Adaptive Writing Tool',
    description: 'An ergonomic pen grip that assists with handwriting, providing better control and reducing strain for users with arthritis or limited hand strength.',
    price: 24.99,
    category: 'daily-living',
    imageUrl: 'https://i.pinimg.com/736x/78/ab/22/78ab221cbdc2feffe7849f810e6994c9--pencil-grip-pencil-holders.jpg',
  },
  {
    id: 10,
    name: 'Spinal Support Body Brace',
    description: 'An orthotic brace that provides robust support for the spine and torso, promoting correct posture and stability.',
    price: 132.25,
    category: 'support',
    imageUrl: 'https://th.bing.com/th/id/OIP.b5oYzylv32c0dUu7zBc7zwHaHa?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 11,
    name: 'Custom-Molded Wheelchair Seat',
    description: 'A custom-fit seating solution with lateral supports and harnesses to provide maximum stability and correct posture in a wheelchair.',
    price: 1499,
    category: 'support',
    imageUrl: 'https://th.bing.com/th/id/R.c9fc0f911667be00f39aacb9dfbedec4?rik=onA6JytzILti5A&riu=http%3a%2f%2fwww.freedomconcepts.com%2fwp-content%2fuploads%2f2017%2f01%2fLaterals_2_FreedomConcepts_800x500.jpg&ehk=4qD21UMyv0Z00HLtsd0YD5R3U3KX5g8oIPcprh%2bSKdw%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    id: 12,
    name: 'GlideSafe Transfer Board',
    description: 'A durable, low-friction board that helps an individual slide safely from one surface to another, such as from a bed to a wheelchair.',
    price: 135.24,
    category: 'mobility',
    imageUrl: 'https://m.media-amazon.com/images/I/719227oKwmL.jpg',
  },
  {
    id: 13,
    name: 'Lightweight Electric Wheelchair',
    description: 'A foldable and portable electric wheelchair providing mobility with an easy-to-use joystick control and long-lasting battery.',
    price: 563.55,
    category: 'mobility',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZcSyBcYhL.jpg',
  },
  {
    id: 14,
    name: 'Pro-Walker with Seat',
    description: 'A sturdy walker for individuals who need support to walk, featuring a built-in seat and storage pouch for convenience.',
    price: 90.17,
    category: 'mobility',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0021/5692/0919/products/standing_living-room_Red_750x.jpg?v=1593802417',
  },
  {
    id: 16,
    name: 'Zenith Prosthetic Leg',
    description: 'A state-of-the-art artificial limb that enables natural walking, designed for comfort, durability, and performance.',
    price: 1690.64,
    category: 'mobility',
    imageUrl: 'https://propelphysiotherapy.com/wp-content/uploads/2024/11/above-knee-amputation-rehabilitation-propel-physiotherapy-200x113.jpg',
  },
   {
    id: 17,
    name: 'Serene Smart Fitness Tracker',
    description: 'A wearable smartwatch that tracks heart rate, HRV, and sleep patterns. Connects to an app to identify stress triggers and provide guided breathing exercises.',
    price: 56.35,
    category: 'mental-health',
    imageUrl: 'https://th.bing.com/th/id/R.0b45845a685270f9728208f342d9dc97?rik=P6Dz9nBVcwYnkA&pid=ImgRaw&r=0',
  },
  {
    id: 18,
    name: 'Biofeedback HeadBand',
    description: 'A tool that monitors physiological responses like brainwaves and provides real-time feedback, helping users learn to control their responses to reduce anxiety.',
    price: 507.18,
    category: 'mental-health',
    imageUrl: 'https://m.media-amazon.com/images/I/71m47mIfE4L._AC_SL1500_.jpg',
  },
  {
    id: 19,
    name: 'SAD Light Therapy Lamp',
    description: 'Emits bright, full-spectrum light to mimic natural sunlight, helping to regulate mood and energy levels, particularly for Seasonal Affective Disorder.',
    price: 50.72,
    category: 'mental-health',
    imageUrl: 'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRe3jN6g334YU_kzZ10luwlr4HQ22evygja79xGCUV_YzDStPAPdwQ6T0M0KrhRkfJ1WLsYIzhJDCZQ5-4HPX9NMm5Tclx-j5MCDN24SwmUFrsApIo',
  },
  {
    id: 20,
    name: 'Acoustic-Shield Noise-Canceling Headphones',
    description: 'Reduce distracting background noise to create a more focused environment for work, study, or relaxation. Essential for managing sensory overload.',
    price: 45.08,
    category: 'mental-health',
    imageUrl: 'https://thegadgetflow.com/wp-content/uploads/2022/12/1MORE-SonoFlow-Active-Noise-Canceling-Headphones-03-1200x900.jpeg',
  }
];